name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: flask-app
  DOCKER_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Debug secret presence
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "Username not found"; else echo "Username exists"; fi
          if [ -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]; then echo "Password not found"; else echo "Password exists"; fi

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: Debug secrets (for testing only, then delete)
        run: |
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Password is set: ${{ secrets.DOCKERHUB_PASSWORD != '' }}"
