name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger only on main branch

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest
