name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your branch

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  PORT: ${{ secrets.PORT }}

  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DOCKER_TAG: ${{ secrets.DOCKER_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$DOCKER_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$DOCKER_TAG
